config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#show'

  resources :portfolios do
    resources :complaints, only: :index
    resources :violations, only: :index
  end
  resources :portfolios do
    resources :buildings
  end
  resources :buildings do
    resources :inspection_rules, only: :index do
      resources :inspections, only: :index
    end
    resources :complaints, only: %i[index update]
    resources :violations, only: %i[index update]
    resources :inspections, only: %i[index]
    resources :upcoming_inspections, only: %i[index update]
  end

  resources :inspections, only: %i[create]
  resources :attachments, only: [:destroy]
  resources :users
  resources :leads do
    collection do
      get :generate_pdf
    end
  end
  resources :user_profiles, only: :update
end

app/models/violations/dob_ecb_violation.rb
# frozen_string_literal: true

module Violations
  class DobEcbViolation < Violation
    def self.mapped_severity(severity)
      case severity
      when 'CLASS - 3, Non-Hazardous'
        0
      when 'CLASS - 2', 'Hazardous'
        1
      when 'CLASS - 1'
        2
      end
    end

    def self.mapped_state(state)
      case state
      when 'ACTIVE'
        0
      when 'RESOLVE'
        2
      end
    end
  end
end

app/models/violations/dob_safety_violation.rb
# frozen_string_literal: true

module Violations
  class DobSafetyViolation < Violation
    def self.mapped_state(state)
      case state
      when 'Active'
        0
      when 'Dismissed'
        2
      end
    end
  end
end

app/models/violations/hpd_violation.rb
# frozen_string_literal: true

module Violations
  class HpdViolation < Violation
    def self.mapped_state(state)
      case state
      when 'Open'
        0
      when 'Close'
        2
      end
    end
  end
end

app/models/violations/violation.rb
# frozen_string_literal: true

module Violations
  class Violation < ApplicationRecord
    include Attachable

    belongs_to :building
    has_many_attached :attachments, dependent: :destroy
    has_many :notifications, as: :notifiable, dependent: :destroy

    validates :violation_id, :building_id, presence: true
    # after_commit :send_notification, on: :create

    audited

    enum severity: {
      non_hazardous: 0,
      hazardous: 1,
      immediately_hazardous: 2
    }

    enum state: {
      open: 0,
      in_progress: 1,
      closed: 2
    }

    private

    def send_notification
      ViolationNotifierJob.perform_later id
    end
  end
end

app/controllers/violations_controller.rb
# frozen_string_literal: true

class ViolationsController < ApplicationController
  load_and_authorize_resource class: 'Violations::Violation'
  load_and_authorize_resource :building, only: :index
  load_and_authorize_resource :portfolio, only: :index

  def index
    @violations = @building.violations.includes(:attachments_attachments, :audits)
    @violations = @violations.send(params[:state]) if params[:state].present?
    if params[:search].present?
      search = "%#{params[:search].strip}%"
      @violations = @violations.where('violation_id LIKE ? OR description LIKE ?', search, search)
    end
    @violations = @violations.order(issue_date: :desc, id: :asc).page(params[:page])
    @violations = PaginationDecorator.decorate(@violations)
  end

  def update
    modifiable_params = violation_params.dup

    modifiable_params[:resolved_date] = nil unless modifiable_params[:state] == 'closed'

    if @violation.update(modifiable_params)
      flash[:success] = t(:violation_update_success)
    else
      flash[:danger] = @violation.errors.full_messages
    end
  end

  private

  def violation_params
    params.require(:violations_violation).permit(:state, :resolved_date, :attachments, :audit_comment, :building_id,
                                                 attachments: [])
  end
end

app/views/violations/_edit.html.erb
<div class="modal fade modal-lg" id="editViolationModal-<%= violation.id %>" tabindex="-1" aria-hidden="true" data-controller="modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Violation</h5>
        <button type="button" class="btn-close" data-action="modal#close" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="error-<%= violation.id %>"></div>

        <!--begin::Form-->
        <%= form_for(violation, url: building_violation_path(@building, violation), remote: true) do |f| %>
          <%= render partial: 'form', locals: { f: f } %>
        <% end %>
        <!--end::Form-->
      </div>
    </div>
  </div>
</div>

app/views/violations/_form.html.erb
<!--begin::Card body-->
<div class="card-body">
  <div class="row">
    <!--begin::First Column - Non-date fields-->
    <div class="col-md-12">
      <!--begin::Input group 1-->
      <div class="row mb-4 align-items-center">
        <label class="col-lg-3">Status</label>
        <div class="col-lg-9">
          <%= f.select :state, Violations::Violation.states.keys.map { |state| [state.titleize, state] }, { selected: f.object.object.state }, { class: 'form-control form-control-lg form-select', id: "state-select-#{f.object.id}" } %>

        </div>
      </div>
      <!--end::Input group 1-->

      <!--begin::Input group 2-->
      <div class="row mb-4 align-items-center" id="filing-date-group-<%= f.object.id %>">
        <label class="col-lg-3">Resolved Date</label>
        <div class="col-lg-9">
          <%= f.date_field :resolved_date, class: 'form-control form-control-lg' %>
        </div>
      </div>
      <!--end::Input group 2-->

      <!--begin::Input group 2-->
      <div class="row mb-12 align-items-center">
        <label class="col-lg-3">Attachments</label>
        <div class="col-lg-9">
          <%= f.file_field :attachments, multiple: true, class: 'form-control form-control-lg' %>
          <div class="form-text">In the file dialog Control Click (Windows) or Command Click (Mac) to select multiple files</div>

        </div>
      </div>
      <!--end::Input group 2-->

      <!--begin::Input group 3-->
      <div class="row align-items-center">
        <label class="col-lg-3 required">Comment</label>
        <div class="col-lg-9">
          <%= f.text_area :audit_comment, class: 'form-control form-control-lg', required: true, rows: 4 %>
        </div>
      </div>
      <!--end::Input group 3-->
    </div>
    <!--end::First Column-->
  </div>

  <%= f.hidden_field :building_id, value: @building&.id %>

  <% f.object.attachments.each do |attachment| %>
    <%= hidden_field_tag 'violations_violation[attachments][]', attachment.signed_id %>
  <% end %>
  <%= hidden_field_tag :state, params[:state] %>
</div>
<!--end::Card body-->

<div class="card-footer d-flex justify-content-end">
  <%= link_to 'Cancel', '#', data: { controller: 'modal', action: 'modal#close' }, class: 'btn btn-light btn-active-light-light me-2' %>
  <%= f.submit 'Save', class: "btn btn-success" %>
</div>
<!--end::Actions-->

app/views/violations/index.html.erb
<div>
  <div class="py-lg-8">
    <h2><%= @building&.name %> Violations (<%= @violations.try(:total_count) %>)</h2>
  </div>

  <!-- Filter Form -->
  <div class="card">
    <div class="d-flex border-0 p-6">
      <div class="me-auto">
        <%= form_with method: :get, local: true do %>
          <div class="d-flex flex-wrap gap-2">
            <div class="search-container">
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
            </div>
            <div class="filter-container">
              <%= select_tag :state, options_for_select(Violations::ViolationDecorator.states_select, params[:state]), class: "form-select" %>
            </div>
            <div class="button-container">
              <%= submit_tag "Filter", class: "btn btn-primary w-100" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>


    <!-- Violations Table -->
    <div class="card-body">
      <div>
        <table class="table align-middle table-row-dashed gy-3">
          <thead>
          <tr class="text-muted fw-bold text-uppercase">
            <th>Violation ID</th>
            <th>Issue Date</th>
            <th>Description</th>
            <th class="d-none d-md-table-cell">Resolved Date</th> <!-- Hidden on mobile -->
            <th class="d-none d-md-table-cell">Attachments</th>
            <th class="d-none d-md-table-cell">Severity</th> <!-- Hidden on mobile -->
            <th>Status</th>
            <th></th> <!-- Hidden on mobile -->
          </tr>
          </thead>
          <tbody>
          <% @violations.each do |violation| %>
            <tr>
              <td><%= violation.violation_id %></td>
              <td><%= violation.issue_date&.strftime("%D") %></td>
              <td><%= violation.description&.truncate(100) %></td>
              <td class="d-none d-md-table-cell"><%= violation.resolved_date&.strftime("%D") %></td>
              <td class="d-none d-md-table-cell">
                <% violation.attachments.each do |attachment| %>
                  <a href="<%= url_for(attachment) %>" download title="<%= attachment.filename.to_s %>">
                    <i class="<%= file_icon_class(attachment) %>"></i>
                  </a>
                <% end %>
              </td>
              <td class="d-none d-md-table-cell"><%= violation.severity %></td>
              <td><%= violation.state %></td>
              <td class="text-end d-none d-md-table-cell">
                <div class="dropdown">
                  <button class="btn btn-sm btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown">
                    Actions
                  </button>
                  <div class="dropdown-menu">
                    <% if can?(:read, violation.object) %>
                      <%= link_to 'View Details', '#', class: 'dropdown-item', data: { controller: 'modal', action: 'modal#open', bs_target: "#violationModal-#{violation.id}" } %>
                    <% end %>
                    <% if can?(:edit, violation.object) %>
                      <%= link_to 'Edit', '#', class: 'dropdown-item', data: { controller: 'modal', action: 'modal#open', bs_target: "#editViolationModal-#{violation.id}" } %>
                    <% end %>
                  </div>
                </div>
              </td>
            </tr>
            <%= render 'edit', violation: violation %>
          <% end %>
          </tbody>
        </table>
      </div>

      <div class="d-flex justify-content-center mt-4">
        <%= paginate @violations, theme: 'bootstrap4' %>
      </div>
    </div>
  </div>
  <!-- Violation Modals -->
  <% @violations.each do |violation| %>
    <div class="modal fade" id="violationModal-<%= violation.id %>" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="fw-bold">Violation Details</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-md-6">
                <p><strong>Violation ID:</strong> <%= violation.violation_id %></p>
                <p><strong>Device Number:</strong> <%= violation.device_number %></p>
                <p><strong>Device Type:</strong> <%= violation.device_type %></p>
                <p><strong>Description:</strong> <%= simple_format(violation.description) %></p>
                <p><strong>Status:</strong> <%= violation.state %></p>
                <p><strong>Issue Date:</strong> <%= violation.issue_date&.strftime("%D") %></p>
                <p><strong>Severity:</strong> <%= violation.severity %></p>
                <p><strong>Updated On:</strong> <%= violation.updated_at&.strftime("%D") %></p>
              </div>
              <div class="col-md-6">
                <h5>Attachments</h5>
                <ul class="list-group">
                  <% violation.attachments.each do |attachment| %>
                    <li class="list-group-item">
                      <%= link_to attachment.filename.to_s, rails_blob_path(attachment, disposition: 'attachment'), target: '_blank' %>
                      <% if can?(:destroy, attachment) %>
                        <%= link_to '#', data: { controller: 'modal', action: 'modal#open', bs_target: "#deleteAttachmentModal-#{attachment.id}" } do %>
                          <i class="bi bi-trash text-danger"></i>
                        <% end %>
                      <% end %>
                    </li>
                    <%= render 'attachments/delete', attachment: attachment %>
                  <% end %>
                </ul>
              </div>
            </div>

            <% if violation.audits.any? { |audit| audit.comment.present? } %>
              <div class="row mt-4">
                <hr>
                <div class="col-lg-12">
                  <h5>Comments</h5>
                  <% violation.audits.each do |audit| %>
                    <% if audit.comment.present? %>
                      <div>
                        <i><%= "#{audit.user.first_name}:" %></i> <%= audit.comment %>
                        <span class="text-muted">(<%= time_ago_in_words(audit.created_at) %> ago)</span>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/violations/update.js.erb
<% if flash[:success] %>
  window.location.href = "<%= building_violations_path(@violation.building, state: params[:state]) %>";
<% else %>
  <% flash[:danger].each do |message| %>
    document.getElementById('error-<%= @violation.id %>').innerHTML += "<div class='alert alert-primary alert-dismissible'><%= j(message) %></div>";
  <% end %>
<% end %>