config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#show'

  resources :portfolios do
    resources :complaints, only: :index
    resources :violations, only: :index
  end
  resources :portfolios do
    resources :buildings
  end
  resources :buildings do
    resources :inspection_rules, only: :index do
      resources :inspections, only: :index
    end
    resources :complaints, only: %i[index update]
    resources :violations, only: %i[index update]
    resources :inspections, only: %i[index]
    resources :upcoming_inspections, only: %i[index update]
  end

  resources :inspections, only: %i[create]
  resources :attachments, only: [:destroy]
  resources :users
  resources :leads do
    collection do
      get :generate_pdf
    end
  end
  resources :user_profiles, only: :update
end

app/views/layouts/partials/_content.html.erb
<% flash.each do |key, value| %>
  <% next unless value.is_a?(String) %>
  <div class="alert alert-<%= key %> alert-dismissible" id="alert"><%= value %></div>
<% end %>

<%= yield %>

app/views/layouts/partials/_footer.html.erb
<!--begin::Footer-->
<div id="kt_app_footer" class="app-footer  align-items-center justify-content-center justify-content-md-between flex-column flex-md-row py-3 py-lg-6 " >
            <!--begin::Copyright-->
<div class="text-dark order-2 order-md-1">
    <span class="text-muted me-1"><%=Time.zone.now.year %>&copy;</span>
    <a href="https://propmaticly.com" target="_blank" class="text-gray-800 text-hover-primary">Propmaticly</a>
</div>
<!--end::Copyright-->
</div>
<!--end::Footer-->

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid p-2 d-flex align-items-center">

    <!-- Logo: Full Width on Mobile, Normal on Larger Screens -->
    <div class="d-flex align-items-center w-100 w-lg-auto">
      <%= link_to root_path, class: "flex-grow-1 text-center text-lg-start" do %>
        <%= image_tag('logo.png', height: '50') %>
      <% end %>

      <!-- Waffle Icon (Navbar Toggler) for Mobile -->
      <button class="navbar-toggler ms-2 d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>

    <!-- Collapsible Navbar Content -->
    <div class="collapse navbar-collapse justify-content-between" id="navbarContent">
      <!-- Navigation Links -->
      <ul class="navbar-nav align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item h5">
            <%= link_to "Dashboard", root_path, class: "me-4" %>
          </li>
          <% if current_user&.admin? %>
            <li class="nav-item h5">
              <%= link_to "Users", users_path, class: "me-4" %>
            </li>
          <% end %>
          <% if can?(:manage, Lead) %>
            <li class="nav-item h5">
              <%= link_to "Leads", leads_path, class: "me-4" %>
            </li>
          <% end %>
        <% end %>
      </ul>

      <!-- Right-Aligned User Dropdown (Hidden on Mobile) -->
      <ul class="navbar-nav ms-auto d-none d-lg-block">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
              Hello, <%= current_user&.first_name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <% unless current_user.admin? %>
                <li>
                  <%= link_to 'Edit Profile', '#', class: 'dropdown-item', data: { controller: 'modal', action: 'modal#open', bs_target: "#editUserProfileModal-#{current_user.id}" } %>
                </li>
                <li><hr class="dropdown-divider"></li>
            <% end %>
              <li>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item text-danger" %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= render('user_profiles/edit', user: current_user) if current_user && !current_user.admin? %>