config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#show'

  resources :portfolios do
    resources :complaints, only: :index
    resources :violations, only: :index
  end
  resources :portfolios do
    resources :buildings
  end
  resources :buildings do
    resources :inspection_rules, only: :index do
      resources :inspections, only: :index
    end
    resources :complaints, only: %i[index update]
    resources :violations, only: %i[index update]
    resources :inspections, only: %i[index]
    resources :upcoming_inspections, only: %i[index update]
  end

  resources :inspections, only: %i[create]
  resources :attachments, only: [:destroy]
  resources :users
  resources :leads do
    collection do
      get :generate_pdf
    end
  end
  resources :user_profiles, only: :update
end

app/models/inspection.rb
# frozen_string_literal: true

class Inspection < ApplicationRecord
  include Attachable

  belongs_to :inspection_rule, class_name: 'InspectionRules::InspectionRule'
  belongs_to :building
  has_many_attached :attachments, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy

  audited

  scope :open, -> { where(state: :open) }
  scope :overdue, -> { where('due_date <= ?', Date.today) }
  scope :complete, -> { where.not(filing_date: nil) }
  scope :incomplete, -> { where(filing_date: nil) }

  validates :inspection_rule_id, :building_id, presence: true

  enum state: { open: 0, in_progress: 1, closed: 2 }
end

app/controllers/inspections_controller.rb
# frozen_string_literal: true

class InspectionsController < ApplicationController
  load_and_authorize_resource only: %i[update destroy]
  load_and_authorize_resource :building, only: :index
  load_and_authorize_resource :inspection_rule, class: 'InspectionRules::InspectionRule', only: :index

  after_action :trigger_create_upcoming_inspections_job, only: :create

  def index
    @inspections = @building.inspections.includes(:attachments_attachments,
                                                  :audits).complete.where(inspection_rule_id: @inspection_rule.id)

    if params[:search].present?
      search = "%#{params[:search].strip}%"
      @inspections = @inspections.where('data::text ILIKE ?', "%#{search}%")
    end

    @inspections = @inspections.order(filing_date: :desc, id: :asc).page(params[:page])
    @inspections = PaginationDecorator.decorate(@inspections)
    @inspection_rule = @inspection_rule.decorate
  end

  def create
    inspection_rule = InspectionRules::InspectionRule.find(inspection_params[:inspection_rule_id])
    @inspection = Inspection.new(inspection_params)

    device_key = InspectionRules::InspectionRule::DEVICE_IDENTIFIER[inspection_rule.compliance_item.to_sym]

    if device_key && device_key != 'device_id'
      device_key = device_key&.split("->>'")&.last&.delete_suffix("'")
      @inspection['data'][device_key] = inspection_params[:device_id]
      @inspection['data']['filing_date'] = inspection_params[:filing_date]
      @inspection['data']['inspection_date'] = inspection_params[:filing_date]
    end

    return unless @inspection.save

    flash[:success] = t(:inspection_create_success)
  end

  private

  def inspection_params
    params.require(:inspection).permit(:device_id, :filing_date, :inspection_rule_id,
                                       :building_id).merge({ state: :closed })
  end

  def trigger_create_upcoming_inspections_job
    CreateUpcomingInspectionsJob.perform_later(building_id: @building)
  end
end

app/views/inspections/_delete.html.erb
<div class="modal fade" id="deleteModal<%= inspection.id %>" data-controller="modal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm Deletion</h5>
        <button type="button" class="btn-close" data-action="modal#close" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this inspection?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-action="modal#close">Cancel</button>
        <%= button_to 'Delete', building_inspection_path(@building, inspection), method: :delete, class: 'btn btn-danger', form: { id: "delete_inspection_#{inspection.id}" } %>
      </div>
    </div>
  </div>
</div>

app/views/inspections/_form.html.erb
<!--begin::Card body-->
<div class="card-body">
  <!--begin::Input group row-->
  <div class="row">
    <!-- First Column -->
      <!--begin::Input group-->
      <div class="row mb-6 align-items-center">
        <label class="col-lg-4 required">Device ID</label>
        <div class="col-lg-8">
          <%= f.text_field :device_id, required: true, class: 'form-control form-control-lg', placeholder: 'Montefiore Residents' %>
        </div>
      </div>
      <!--end::Input group-->

      <!--begin::Input group-->
      <div class="row mb-6 align-items-center">
        <label class="col-lg-4 required">Last Inspection Date</label>
        <div class="col-lg-8">
          <%= f.date_field :filing_date, required: true, class: 'form-control form-control-lg', placeholder: '3450' %>
        </div>
      </div>
      <!--end::Input group-->
    <!-- End First Column -->
  </div>
  <!--end::Input group row-->
  <%= f.hidden_field :inspection_rule_id, value: @inspection_rule&.id %>
  <%= f.hidden_field :building_id, value: @building&.id %>
</div>
<!--end::Card body-->

<!--begin::Actions-->
<div class="card-footer d-flex justify-content-end py-6 px-9">
  <%= link_to 'Cancel', '#', data: { controller: 'modal', action: 'modal#close' }, class: 'btn btn-light btn-active-light-light me-2' %>
  <%= f.submit 'Save', class: "btn btn-success" %>
</div>
<!--end::Actions-->

app/views/inspections/_new.erb
<div class="modal fade modal-lg" id="newModal" tabindex="-1" aria-hidden="true" data-controller="modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add Inspection</h5>
        <button type="button" class="btn-close" data-action="modal#close" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="error">
        </div>

        <%= form_for(inspection = Inspection.new, remote: true) do |f| %>
          <%= render partial: 'form', locals: { f: f, inspection: inspection, inspection_rule_id: @inspection_rule&.id, building_id: @building&.id } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/inspections/create.js.erb
<% if flash[:success] %>
  window.location.href = "<%= building_inspection_rule_inspections_path(@inspection.building, @inspection.inspection_rule) %>";
<% else %>
  <% flash.each do |key, message| %>
    document.getElementById('error').innerHTML += "<div class='alert alert-primary alert-dismissible'><%= j(message) %></div>";
    document.getElementById('error-<%= @inspection.id %>').innerHTML += "<div class='alert alert-primary alert-dismissible'><%= j(message) %></div>";
  <% end %>
<% end %>

app/views/inspections/index.html.erb
<div>
  <!-- Page Header -->
  <div class="py-lg-8">
    <h2><%= @building&.name %>: Past <%= @inspection_rule&.compliance_item_humanize %> Inspections (<%= @inspections.try(:total_count) %>)</h2>
  </div>

  <!-- Inspection Search & Add Button -->
  <div class="card">
    <div class="d-flex flex-wrap justify-content-between p-6">
      <div class="me-auto">
        <%= form_with url: building_inspection_rule_inspections_path(@building, @inspection_rule), method: :get, local: true do %>
          <div class="d-flex flex-wrap gap-2">
            <div class="search-container">
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
            </div>
            <div class="button-container">
              <%= submit_tag "Search", class: "btn btn-primary w-100" %>
            </div>
          </div>
        <% end %>
      </div>

      <% if can?(:create, Inspection.new(inspection_rule_id: @inspection_rule.id)) %>
        <%= link_to 'Add Inspection', '#', class: 'btn btn-success' , data: { controller: 'modal', action: 'modal#open', bs_target: "#newModal" } %>
      <% end %>
    </div>

    <!-- Inspections Table -->
    <div class="card-body">
      <div>
        <table class="table align-middle table-row-dashed gy-3">
          <%= @inspection_rule.header_html %>
          <tbody>
          <% @inspections.each do |inspection| %>
            <tr>
              <% if inspection.data.present? %>
                <% @inspection_rule.headers.each do |attribute| %>
                  <td><%= inspection.data_value(attribute) %></td>
                <% end %>
              <% else %>
                <td><%= inspection.device_id %></td>
                <% (@inspection_rule.headers.size - 2).times do %>
                  <td></td>
                <% end %>
                <td><%= inspection.filing_date&.strftime('%D') %></td>
            <% end %>
              <td class="d-none d-md-table-cell">
                <div class="dropdown">
                  <button class="btn btn-sm btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Actions
                  </button>
                  <div class="dropdown-menu">
                    <% if can?(:read, inspection.object) %>
                      <li><%= link_to 'View Details', '#', class: 'dropdown-item', data: { controller: 'modal', action: 'modal#open', bs_target: "#inspectionModal-#{inspection.id}" } %></li>
                    <% end %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <!-- Pagination -->
      <div class="d-flex justify-content-center mt-4">
        <%= paginate @inspections, theme: 'bootstrap4' %>
      </div>
      <%= render 'new' %>
    </div>
  </div>

  <!-- Modals for Inspection Details -->
  <% @inspections.each do |inspection| %>
    <div class="modal fade" id="inspectionModal-<%= inspection.id %>" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="fw-bold"><%= inspection.inspection_rule.decorate.compliance_item_humanize %> Inspection Details</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="row">
              <% if inspection.data.present? %>
                <% inspection.data.keys.sort.each_slice(10) do |chunk| %>
                  <div class="col-md-6">
                    <% chunk.each do |key| %>
                      <p><strong><%= key.titleize %>: </strong><%= inspection.data[key] %></p>
                    <% end %>
                  </div>
                <% end %>
              <% else %>
                <div class="col-md-6">
                  <p><strong>Device ID: </strong><%= inspection.device_id %></p>
                  <p><strong>Filing Date: </strong><%= inspection.filing_date&.strftime('%D') %></p>
                </div>
              <% end %>
            </div>
            <p><strong>Updated On:</strong> <%= inspection&.updated_at&.strftime("%D") %></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>